# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# ================ Platform ================

default_platform(:android)

# ================ Lanes ================

platform :android do

  before_all do
    clean_reports()
  end

  desc "Detekt checks"
  lane :detekt do
    run_detekt()
  end

  desc "Runs all tests in all modules"
  lane :test_all do
    run_all_tests()
  end

# ================ Gradle tasks ================

  def run_detekt
    gradle(task: "detekt --continue")
  end

  def clean_reports
    gradle(task: "removeReports")
  end

  def run_all_tests
    gradle(task: "clean test --continue")
  end
end
